module.exports = [
    {
        name: "bulbasaur",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ivysaur",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "venusaur",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "charmander",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "charmeleon",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "charizard",
        types: ["fire", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "squirtle",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "wartortle",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "blastoise",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "caterpie",
        types: ["bug"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "metapod",
        types: ["bug"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "butterfree",
        types: ["bug", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "weedle",
        types: ["bug", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kakuna",
        types: ["bug", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "beedrill",
        types: ["bug", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "pidgey",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "pidgeotto",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "pidgeot",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ratata",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "raticate",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "spearow",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "fearow",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ekans",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "arbok",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "pikachu",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "raichu",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "sandshrew",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "sandslash",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidoran-f",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidorina",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidoqueen",
        types: ["poison", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidoran-m",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidorino",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "nidoking",
        types: ["poison", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "clefairy",
        types: ["fairy"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "clefable",
        types: ["fairy"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "vulpix",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ninetails",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "jigglypuff",
        types: ["normal", "fairy"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "wigglytuff",
        types: ["normal", "fairy"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "zubat",
        types: ["poison", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "golbat",
        types: ["poison", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "oddish",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "gloom",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "vileplume",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "paras",
        types: ["bug", "grass"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "parasect",
        types: ["bug", "grass"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "venonat",
        types: ["bug", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "venomoth",
        types: ["bug", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "diglet",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dugtrio",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "meowth",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "persian",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "psyduck",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "golduck",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "mankey",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "primeape",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "growlithe",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "arcanine",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "poliwag",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "poliwhirl",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "poliwrath",
        types: ["water", "fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "abra",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kadabra",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "alakazam",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "machop",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "machoke",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "machamp",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "bellsprout",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "weepinbell",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "victreebel",
        types: ["grass", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "tentacool",
        types: ["water", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "tentacruel",
        types: ["water", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "geodude",
        types: ["rock", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "graveler",
        types: ["rock", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "golem",
        types: ["rock", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ponyta",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "rapidash",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "slowpoke",
        types: ["water", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "slowbro",
        types: ["water", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "magnemite",
        types: ["electric", "steel"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "magneton",
        types: ["electric", "steel"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "farfetch'd",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "doduo",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dodrio",
        types: ["normal", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "seel",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dewgong",
        types: ["water", "ice"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "grimer",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "muk",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "shellder",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "cloyster",
        types: ["water", "ice"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "gastly",
        types: ["ghost", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "haunter",
        types: ["ghost", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "gengar",
        types: ["ghost", "poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "onix",
        types: ["rock", "ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "drowzee",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "hypno",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "krabby",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kingler",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "voltorb",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "electrode",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "exeggcute",
        types: ["grass", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "exeggutor",
        types: ["grass", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "cubone",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "marowak",
        types: ["ground"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "hitmonlee",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "hitmonchan",
        types: ["fighting"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "lickitung",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "koffing",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "weezing",
        types: ["poison"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "rhyhorn",
        types: ["ground", "rock"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "rhydon",
        types: ["ground", "rock"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "chansey",
        types: ["chansey"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "tangela",
        types: ["grass"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kangaskhan",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "horsea",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "seadra",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "goldeen",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "seaking",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "staryu",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "starmie",
        types: ["water", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "mr. mime",
        types: ["psychic", "fairy"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "scyther",
        types: ["bug", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "jynx",
        types: ["ice", "psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "electabuzz",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "magmar",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "pinsir",
        types: ["bug"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "tauros",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "magikarp",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "gyarados",
        types: ["water", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "lapras",
        types: ["water", "ice"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "ditto",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "eevee",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "vaporeon",
        types: ["water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "jolteon",
        types: ["electric"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "flareon",
        types: ["fire"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "porygon",
        types: ["rock"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "omanyte",
        types: ["rock", "water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "omastar",
        types: ["rock", "water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kabuto",
        types: ["rock", "water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "kabutops",
        types: ["rock", "water"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "aerodactyl",
        types: ["rock", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "snorlax",
        types: ["normal"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "articuno",
        types: ["ice", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "zapdos",
        types: ["electric", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "moltres",
        types: ["fire", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dratini",
        types: ["dragon"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dragonair",
        types: ["dragon"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "dragonite",
        types: ["dragon", "flying"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "mewtwo",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    },
    {
        name: "mew",
        types: ["psychic"],
        moves: [],
        abilities: [],
        spriteURL: "", 
        genaration: "I",
    }
]